### ISSUE TITLE
Read/Write .w3u

### ISSUE THREAD

**Issue by jejanim** [cipherxof/wc3-ts-template#9]
I just found out about https://github.com/nvs/map which, if I understand the radme correctly, can do just that (see headline), albeit in lua only.
Would be great if we could do that here too (or at least provide the option) so we can create predefined units programmatically.

I'm not a great fan of lua there myself, but would be willing to help.

Maybe if 

- https://github.com/invokerrrr/war3map or
- https://github.com/ChiefOfGxBxL/WC3MapTranslator

can do it, that'd be a good starting point.

**Comment by cipherxof** [comment]
I already have a compile time object api in the works

**Comment by jejanim** [comment]
Awesome, count me in when looking for testers.
